### ISSUE TITLE
Zend\Http\Header\AbstractAccept, "undefined offset: 1" for some accept headers

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-http#10]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7352
User: @jurajseffer
Created On: 2015-03-21T13:59:27Z
Updated At: 2015-11-06T21:19:42Z
Body
ZF version tested on: 2.3.3

An application sometimes receives the following (invalid?) accept header:

```
Accept: text/html,application/xhtml+xml,application/xml;image/png,image/jpeg,image/*;q=0.9,*/*;q=0.8
```

This causes an "Undefined offset: 1" notice on line 174 in Zend\Http\Header\AbstractAccept

```
$value = trim($explode[1]);
```

---

---

Originally posted by @GeeH at https://github.com/zendframework/zend-http/issues/73

**Comment by samsonasik** [comment]
it seems already handled at https://github.com/laminas/laminas-http/blob/176e28620407587c8d6b454fe9c81b6d696750a9/src/Header/AbstractAccept.php#L171 with count explode variable check. I am closing it. Please re-create issue if the problem persist.
