### ISSUE TITLE
Request object can't easily be proxied because new headers get overwritten by original request's headers

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-http#19]
Originally zendframework/zendframework#6101

I have an action that proxies the current request by modifying the Uri in the original request and then sending it through Zend\Http\Client. However, the new Host header based on the Uri gets overwritten by the original Host header in the original request.

Eg:

```
//original uri: http://example.com/proxy-request
$request = clone $this->request;
$uri = $request->getUri();
$uri->setHost('target-site.com');
$uri->setPath('/proxy-target');

$client = new Zend\Http\Client();
$response = $client->send($request);
```

The request ends up being sent to http://example.com/proxy-target instead of http://target-site.com/proxy-target

The new host header gets set up in https://github.com/zendframework/zend-http/blob/master/src/Client.php#L1110

But then gets replaced with the header from the request here:
https://github.com/zendframework/zend-http/blob/master/src/Client.php#L1174

Shouldn't the new headers take precedence over the headers from the request?

---

Originally posted by @dkmuir at https://github.com/zendframework/zend-http/issues/64

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> You can continue using laminas/laminas-http safely.
> Its successor will be [PSR-7](https://www.php-fig.org/psr/psr-7/) in a later revision of laminas/laminas-mvc.

**Comment by dkmuir** [comment]
Thanks for the update @weierophinney. PRS-7 only covers messages. Will this new revision include PSR-18 as well?

**Comment by weierophinney** [comment]
@dkmuir No, it will not. There are plenty of PSR-18 implementations already, and we see no reason to provide one ourselves. The primary use case for laminas-http was to provide HTTP messages for the MVC; the client has not had new features in many years, and offers nowhere near the functionality you'll find in most modern PHP HTTP clients.

**Comment by dkmuir** [comment]
@weierophinney Thanks for the heads up.
