### ISSUE TITLE
Better distinguishing between runtime problems

### ISSUE THREAD

**Issue by dpauli** [laminas/laminas-http#36]
Right now all problems in `Http\Client::send()` will happen in one `Client\Adapter\Exception\RuntimeException` with a (often `sprintf`) string and error code `0`.

*Examples:*
```
throw new AdapterException\RuntimeException('Unable to Connect to ' . $host . ':' . $port);
```

```
throw new AdapterException\RuntimeException('Trying to write but we are not connected');
```

With this `Exception` I cannot handle useful reactions in my software.

My Feature Request hopefully triggers the discussion to cluster `Exceptions` or work with `Exception::code` to distinguish problems.

**Comment by weierophinney** [comment]
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/2b55453e172a1b8c9c4c212be7cf7e7a58b9352c/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-components-to-mark-as-security-only).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
>
> You can continue using laminas/laminas-http safely.
> Its successor will be [PSR-7](https://www.php-fig.org/psr/psr-7/) in a later revision of laminas/laminas-mvc.
