### ISSUE TITLE
Laminas client user agent being blocked by some hosts

### ISSUE THREAD

**Issue by Synchro** [laminas/laminas-http#38]
This isn't a bug report, more of a heads-up that may be useful for others that run into it.

I'm using the Laminas Feed component in a system that previously used ZF, and recently we noticed that some RSS feeds had stopped working – this could have happened when we switched to Laminas but we only just spotted it.

I have tracked this down using curl to some sites apparently blocking the Laminas user agent, for example, using curl's default user agent (which is `curl/7.70.0`):

```sh
$ curl -I https://meetedgar.com/blog/feed/                                                                                                                        
HTTP/1.1 200 OK
```

```sh
$ curl -I -H 'User-Agent: Laminas\Http\Client' https://meetedgar.com/blog/feed/
HTTP/1.1 403 Forbidden
```

Further investigation suggests it's the backslashes it doesn't like, as an agent of `a\b` is rejected the same way. Doubling backslashes (`a\\b`) in case it was a shell escaping issue doesn't help. 

Obviously this rejection isn't within Laminas' control, and I have no idea how widespread this issue is; This particular blog is hosted on cloudflare, but other sites I found on cloudflare didn't block these requests; it's also wordpress, but other wordpress sites don't block it. It can be avoided by simply changing the user agent that Laminas uses, either at runtime, or perhaps in Laminas itself; for example `Laminas/Http/Client` works.

**Comment by froschdesign** [comment]
Reference: https://github.com/laminas/laminas-http/blob/45c7a17f210bdd4b5bff8be5479133252b9be697/src/Client.php#L105-L126

**Comment by Synchro** [comment]
Thanks!
