### ISSUE TITLE
`Zend\Http\Response\PhpEnvironment#sendHeaders()` silently returns - should scream and burn and demand for human sacrifices instead

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-http#5]
https://github.com/zendframework/zend-http/blob/b382c6e068a2d9c87b7cf0dfe78c6dd19e4ff197/src/PhpEnvironment/Response.php#L84

To reproduce (sorry if I couldn't do it myself right away - needs a `@runInSeparateProcess` test):

```php
$response = new \Zend\Http\Response\PhpEnvironment();

echo 'foo;
ob_flush();

// expect an exception here
$response->sendHeaders();
```

---

Originally posted by @Ocramius at https://github.com/zendframework/zend-http/issues/138

**Comment by samsonasik** [comment]
@Ocramius I created PR https://github.com/laminas/laminas-http/pull/41 for it.
