### ISSUE TITLE
PHP 8.1: Countable incompatibility for Headers

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-http#55]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.14

#### Summary

PHP Fatal error:  During inheritance of Countable: Uncaught Return type of Laminas\Http\Headers::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

More details can be found here:

https://php.watch/versions/8.1/serializable-deprecated
https://wiki.php.net/rfc/phase_out_serializable

#### Current behavior

Tests are failing.

#### How to reproduce

Execute tests with PHP 8.1

#### Expected behavior

Tests are passing.

**Comment by ramsey** [comment]
Asked about this in the Laminas Slack. Until there's a successor package, I think this means that much of the Laminas ecosystem will not be able to upgrade to PHP 8.1.

https://laminas.slack.com/archives/C4QBQUEG5/p1627577291397400

**Comment by froschdesign** [comment]
@ramsey 
Updates for PHP 8.1 are planned, also for this component.

**Comment by Ocramius** [comment]
Handled in #57
