### ISSUE TITLE
PHP 8.2 deprecation: dynamic property headersSent in PhpEnvironment\Response

### ISSUE THREAD

**Issue by zerocrates** [laminas/laminas-http#74]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.16.1, 2.17.1

#### Summary

PhpEnvironment\Response::sendHeaders sets a dynamic property `$headersSent`.

This emits a deprecation notice on PHP 8.2:

> Deprecated:  Creation of dynamic property Laminas\Http\PhpEnvironment\Response::$headersSent is deprecated in .../laminas/laminas-http/src/PhpEnvironment/Response.php on line 113

The property seems to be unused: the corresponding code that actually checks if headers were sent just uses PHP's headers_sent function and doesn't use this property. The set on line 113 looks to have been accidentally left in place by the long-ago change to use headers_sent which removed the property declaration: e29f84f4c8d659e9076a7c4b9966d6a97324cc52

**Comment by Ocramius** [comment]
Consider sending a patch with a failing test case

**Comment by samsonasik** [comment]
Resolved at https://github.com/laminas/laminas-http/pull/75
