### ISSUE TITLE
New helper function to detect AJAX request without X-Request-With header

### ISSUE THREAD

**Issue by driehle** [laminas/laminas-http#76]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

Nowadays, AJAX libraries tend not to send the `X-Requested-With: XMLHttpRequest` anymore. Following a discussion in axios/axios#1322, the usage of the `Accept` header should be preferred. The `Accept` header has less issues with CORS, as it does not manually need to be whitelisted.

Consequently, the following code present in the [Request class](https://github.com/laminas/laminas-http/blob/2.19.x/src/Request.php) is no longer able to detect such AJAX request:

```php
    public function isXmlHttpRequest()
    {
        $header = $this->getHeaders()->get('X_REQUESTED_WITH');
        return false !== $header && $header->getFieldValue() === 'XMLHttpRequest';
    }
```

What would you think of adding a new method `wantsJson()` as such:

```php
    public function wantsJson()
    {
        $match = $this->getHeaders()->get('Accept')?->match('application/json');
        return 'application/json' === $match?->getTypeString();
    }
```

That can distinguish requests from regular browsers from those of AJAX libraries, as browsers tend to have `*/*` in their accept header, but not `application/json`. Could be a nice feature in 2023.

Open for comments.

**Comment by Ocramius** [comment]
What you want is content negotiation: I endorse doing that with `laminas/diactoros` and PSR-7 though.

For example, see https://github.com/middlewares/negotiation/tree/82a79066b2a78b8fa5fb4210b6f84fe4b9af70e5#contenttype

**Comment by driehle** [comment]
Well, here the case was as follows: Content negotiation happens on the level of MVC controllers. So far, so good. Now there is a logic before that which checks authentication and authorization. If access is denied, browsers receive a 302 redirect to the login page (including a return URL parameter), while Ajax requests should receive a 403 JSON response.

**Comment by Ocramius** [comment]
Fairly sure I've seen people using `laminas/laminas-mvc` for content negotiation via listeners though: no need to touch `laminas/laminas-http` for that :thinking:
