### ISSUE TITLE
Request object from controller is not usable by RequestInterface and PSR-7

### ISSUE THREAD

**Issue by Eugentis** [laminas/laminas-http#79]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.18.0

#### Summary

Hi!

Class `src/Request.php` is not comfortable to use by `Laminas\Stdlib\RequestInterface` interface.
Real object has more public methods in comparison with RequestInterface - for method, uri and others

Do you have any plans to use common PSR interfaces like [RequestInterface](https://github.com/php-fig/http-message/blob/master/src/RequestInterface.php)?

It will be more comfortable to use in this situation.

#### Current behavior

In code you should use [Request](https://github.com/laminas/laminas-http/blob/2.19.x/src/Request.php) class as dependency instead of [RequestInterface](https://github.com/laminas/laminas-stdlib/blob/3.19.x/src/RequestInterface.php)

#### How to reproduce

Try to use `\Laminas\Mvc\Controller\AbstractController::getRequest()` and receive uri by `getUri()` on it and check code by phpstan
#### Expected behavior

RequestInterface is suitable with PSR-7

**Comment by Ocramius** [comment]
Not for `laminas/laminas-http`: use a PSR-18 HTTP client implementation for that instead :)
